image: hashicorp/terraform:1.0.7

pipelines:
  pull-requests:
    feature/*:
      - step:
          name: Confirm successful build
          deployment: dev
          script:
            - apk update && apk add --no-cache unzip curl python3 py3-pip
            - pip3 install awscli
            - aws --version  # Verify the installation
            - aws configure set region $REGION
            - |
              cd $BITBUCKET_CLONE_DIR  # Navigate to the cloned repository directory
              terraform init -backend-config=$ENV_DIR/$ENV/backend.tfvars
              terraform validate
              terraform plan -var-file=$ENV_DIR/$ENV/variable.tfvars

  branches:
    develop:
      - step:
          name: Deploy to Dev
          deployment: dev
          script:
            - apk update && apk add --no-cache unzip curl python3 py3-pip
            - pip3 install awscli
            - aws --version  # Verify the installation
            - aws configure set region $REGION
            - |
              cd $BITBUCKET_CLONE_DIR  # Navigate to the cloned repository directory
              terraform init -backend-config=$ENV_DIR/$ENV/backend.tfvars
              terraform validate
              terraform plan -var-file=$ENV_DIR/$ENV/variable.tfvars
              terraform apply -auto-approve -var-file=$ENV_DIR/$ENV/variable.tfvars

  custom:
    manual-prod-deploy:
      - step:
          name: Manual Deploy to Prod
          deployment: prod
          script:
            - apk update && apk add --no-cache unzip curl python3 py3-pip
            - pip3 install awscli
            - aws --version  # Verify the installation
            - aws configure set region $REGION
            - |
              cd $BITBUCKET_CLONE_DIR  # Navigate to the cloned repository directory
              terraform init -backend-config=$ENV_DIR/$ENV/backend.tfvars
              terraform validate
              terraform plan -var-file=$ENV_DIR/$ENV/variable.tfvars
              terraform apply -auto-approve -var-file=$ENV_DIR/$ENV/variable.tfvars
