region                      = "us-east-1"
prefix_company              = "digi"
lob                         = "internal"
prefix_region               = "use1"
env                         = "prod"
repo_url                    = "https://bitbucket.org/digiclaritydev/belusa-terraform-lambda"