region                      = "us-east-1"
prefix_company              = "digi"
lob                         = "internal"
prefix_region               = "use1"
env                         = "dev"
repo_url                    = "https://github.com/jinsi14/lexbot-terraform-cdk"